#Creating a RGB image  using Pillow Library

In [5]:
from PIL import Image

In [16]:
#for creating a colored image we use RGB=>Red,Blue,Green
img=Image.new("RGB",(100,100),(255,100,0))

In [3]:
print(img)
print(img.size)
print(img.format)
print(img.mode)
print(img.getbands())

<PIL.Image.Image image mode=RGB size=100x100 at 0x2693D059B50>
(100, 100)
None
RGB
('R', 'G', 'B')


In [4]:
img.show()

##Creating a Black/White image  using Pillow Library

In [17]:
#for creating gray scale image we use L means Ligth image
img=Image.new('L',(100,100),(123))

In [14]:
print(img)
print(img.size)
print(img.format)
print(img.mode)
print(img.getbands())

<PIL.Image.Image image mode=L size=100x100 at 0x2693D1A1A30>
(100, 100)
None
L
('L',)


In [15]:
img.show()

#creating  a colored image in opencv using numpy array

In [20]:
import numpy as np
import cv2

In [21]:
img=np.zeros((500,500,3),np.uint8)

In [27]:
img[:]=(255,100,0)

In [24]:
print(img.shape)
print(len(img))

(500, 500, 3)
500


In [25]:
cv2.imshow('Opencv_img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#creating gray scale image in opencv using numpy array

In [62]:
#syntax np.zeros((array_size,each array has->three row_size,and three coloumn_size))
print(np.zeros((3,3,3)),end=" ")

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] 

In [29]:
img=np.zeros((500,500,1),np.uint8)

In [34]:
img[:]=(0)

In [36]:
print(img.shape)
print(len(img))

(500, 500, 1)
500


In [37]:
cv2.imshow('Openc_grey_img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#pillow will supports the alpha value in the RGBA image

In [76]:
image=Image.new("RGBA",(100,100),(255,100,0,25))

In [77]:
print(image)
print(image.size)
print(image.mode)
print(image.getbands())

<PIL.Image.Image image mode=RGBA size=100x100 at 0x2694B55FF80>
(100, 100)
RGBA
('R', 'G', 'B', 'A')


In [79]:
image.show()

#opencv cannot support alpha value we can manually change it

In [82]:
img=np.zeros((500,500,4),np.uint8)

In [83]:
img[:,:,:3]=(250,100,0)

In [89]:
img[:,:,3]=(100)

In [90]:
cv2.imshow("alpha_rgb",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

##defualt opencv read the image in the BGR format

In [91]:
img=cv2.imread("E:\\opencv\\myvenv\\opencv_basics.ipynb\\thala.jpg")

In [ ]:
img.imsh

In [92]:
convert=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [93]:
cv2.imwrite("E:\\opencv\\myvenv\\opencv_basics.ipynb\\thala1.jpg",convert)

True

In [94]:
"""
* JPEG-join photographic Expert Group Image

* PNG-portable NetworksGraphics
"""

'\n* JPEG-join photographic Expert Group Image\n\n* PNG-portable NetworksGraphics\n'